### PR TITLE
Make install output better

### PR DESCRIPTION
**Pull request by friism**
Starting the docker service after the restart doesn't make sense - it'll start automatically.

cc @taylorb-microsoft

### CODE REVIEW

**Comment by jayshah-msft** [comment]
I have added the restart request conditional based on whether containers was installed or not. I need to merge it to the developer branch. Will do that.
I did multiple tests and in some of my tests I saw that the service had not started after the reboot, hence I called it out. 

Cheers,
Jay!

**Comment by friism** [comment]
That'd be strange - it's a normal Windows Server, if that doesn't start, we have bigger problems.

@jayshah-msft if you're still seeing this, can you provide a repro of how the service doesn't start.

**Comment by jayshah-msft** [comment]
As I mentioned it wasn't a consistent repro. But I will run a few more tests and if this does repro, I will forward the steps to you.

Cheers,
Jay!

**Comment by friism** [comment]
rebased

**Comment by jayshah-msft** [comment]
Took this, signed the files and updated the README.md

Cheers,
Jay!

**Pull request merged**
